---
- name: Install several base packages
  hosts: all

  tasks:
  - name: Install Vim git Screen rsync and cowsay
    yum:
      name={{ item }}
      state=present
    with_items:
      - vim
      - git
      - screen
      - rsync
      - cowsay
