---
- hosts:  all
  tasks:
    - name: Install VIM
      #yum: pkg=vim state=present
      apt: pkg=vim state=present
      sudo: yes

    - name: Install Dotfiles
      git:  >
        repo=git@github.com:sergiogoro/dotFiles.git
        dest=/home/${ansible_user_id}/.vim

    - name: Create .vimrc Symlink
      file: >
        src=/home/${ansible_user_id}/.vim/vimrc
        dest=/home/${ansible_user_id}/.vimrc
        state=symlink

    - name: Compile and Install Command-T plugin
      command: >
        rake make
        chdir=/home/${ansible_user_id}/.vim/bundle/Command-T
        creates=/home/${ansible_user_id}/.vim/bundle/Command-T/command-t.recipe



